#!/usr/bin/env python
# coding: utf-8

# In[1]:


from dwave.system import EmbeddingComposite, DWaveSampler


# In[2]:


from braket.aws import AwsDevice
from braket.ocean_plugin import BraketSampler, BraketDWaveSampler
from braket.ocean_plugin import BraketDWaveSampler


# In[3]:


root_bucket= "amazon-braket-us-west-2-175491565676" # the name of the bucketthe name of the bucket (this bucket has to be in us-west-2, so just replace my bucket with ours and it should works)
my_prefix = "D-Wave-test" # the name of the folder in the bucket
hardcoded_folder =  (root_bucket, my_prefix)


# In[4]:


device = AwsDevice("arn:aws:braket:::device/qpu/d-wave/DW_2000Q_6")
print('Device:', device)


# In[5]:


Q = { ('q1', 'q1'): -1.5, ('q2', 'q2'): -0.875, ('q1', 'q2'): 0.5, ('q3', 'q3'): -1.5, ('q1', 'q3'): 0.5, ('q2', 'q3'): 0.25, ('q4', 'q4'): -0.875, ('q1', 'q4'): 0.25, ('q2', 'q4'): 0.125, ('q3', 'q4'): 0.5, ('q5', 'q5'): -2., ('q1', 'q5'): 1., ('q2', 'q5'): 0.5, ('q3', 'q5'): 1., ('q4', 'q5'): 0.5, ('q6', 'q6'): -1.25, ('q1', 'q6'): 0.5, ('q2', 'q6'): 0.25, ('q3', 'q6'): 0.5, ('q4', 'q6'): 0.25, ('q5', 'q6'): 1.}


# In[6]:


sampler = BraketDWaveSampler(hardcoded_folder, device_arn='arn:aws:braket:::device/qpu/d-wave/DW_2000Q_6')
sampler = EmbeddingComposite(sampler)
sampleset = sampler.sample_qubo(Q, num_reads=100)


# In[7]:


print(sampleset)
